title: <p align="center"> Sreejith S </p>

logo: "/images/picture.png?raw=true" 

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/">LinkedIn</a> |
  <a href="https://github.com/sreeji10">GitHub</a>
  </p>
  
  <p align="justify">
  Passionate Software Engineer
  <br><br>
  Currently working on Machine learning projects.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal